AWSTemplateFormatVersion: '2010-09-09-OC'
Description: default template generated for organization with master account 102625093955

Organization:
  ManagementAccount:
    Type: OC::ORG::MasterAccount
    Properties:
      AccountName: Olaf Conijn
      AccountId: '102625093955'
      RootEmail: olaf_conijn@hotmail.com

  OrganizationRoot:
    Type: OC::ORG::OrganizationRoot
    Properties:
      DefaultOrganizationAccessRoleName: OrganizationAccountAccessRole
      ServiceControlPolicies:
        - !Ref DenyChangeOfOrgRoleSCP
        - !Ref DenyOverwriteTagSCP

  AccountCAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Account C
      AccountId: '673026687213'
      RootEmail: account+c@olafconijn.awsapps.com
      OrganizationAccessRoleName: AnotherCustomRole

  AccountBAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Account B
      AccountId: '362239514602'
      RootEmail: account+b@olafconijn.awsapps.com
      OrganizationAccessRoleName: CustomCrossAccountRole

  AccountAAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Account A
      AccountId: '340381375986'
      RootEmail: account+a@olafconijn.awsapps.com

  Account_11Account:
    Type: OC::ORG::Account
    Properties:
      AccountName: account 11
      AccountId: '785762177022'
      RootEmail: stedi-11@stedi.com

  OrganizationBuildAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Organization Build Account
      AccountId: '832731326652'
      RootEmail: ccount+a@olafconijn.awsapps.com
      Tags:
        budget-alarm-threshold-email-recipient: olaf_conijn@hotmail.com
        budget-alarm-threshold: '200'

  SecurityAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Security Account
      AccountId: '152091636325'
      RootEmail: ccount+security@olafconijn.awsapps.com

  LogArchiveAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Log Archive Account
      AccountId: '553475573463'
      RootEmail: ccount+log-archive@olafconijn.awsapps.com

  TestAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: test
      AccountId: '228071492591'
      RootEmail: something@email.com

  UsersAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Users Account
      AccountId: '549476213961'
      RootEmail: account+users@olafconijn.awsapps.com

  DenyS3DeleteBucketSCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: DenyS3DeleteBucket
      Description: Prevents the deletion of s3 buckets
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyS3DeleteBucket
            Effect: Deny
            Action: 's3:DeleteBucket'
            Resource: '*'
        
  DenyChangeOfOrgRoleSCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: DenyChangeOfOrgRole
      Description: Deny changing the IAM role used for organization access
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyChangeOfOrgRole
            Effect: Deny
            Action:
              - 'iam:Attach*'
              - 'iam:Create*'
              - 'iam:Delete*'
              - 'iam:Detach*'
              - 'iam:PutRole*'
              - 'iam:Update*'
            Resource:
              - 'arn:aws:iam::*:role/OrganizationAccountAccessRole'
        
  DenyOverwriteTagSCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: DenyOverwriteTag
      Description: ''
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyOverwritingStediAccountIdTag
            Effect: Deny
            Action: 'iam:TagRole'
            Resource: 'arn:aws:iam::*:role/*'
            Condition:
              'Null':
                'iam:RequestTag/StediAccountId': 'false'
                'iam:ResourceTag/StediAccountId': 'false'
          - Sid: DenyRemovingStediAccountIdTag
            Effect: Deny
            Action: 'iam:UnTagRole'
            Resource: 'arn:aws:iam::*:role/*'
            Condition:
              'Null':
                'aws:RequestTag/StediAccountId': 'false'
        

