AWSTemplateFormatVersion: '2010-09-09-OC'
Description: default template generated for organization with master account 507468909204

Organization:
  MasterAccount:
    Type: OC::ORG::MasterAccount
    Properties:
      AccountName: Organization Master Account
      RootEmail: olaf@email.com
      AccountId: '507468909204'

  SharedUsersAccount:
    Type: OC::ORG::Account
    Properties:
      RootEmail: users-2@olafconijn.awsapps.com
      AccountName: Shared Users Account

  DevelopmentAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Development Account
      RootEmail: dev-account-1@olafconijn.awsapps.com

  Production1Account:
    Type: OC::ORG::Account
    Properties:
      AccountName: Production Account
      RootEmail: production1@olafconijn.awsapps.com